name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  project-testing:
    runs-on: ubuntu-latest
    env:   # 👈 Secrets injected at job level
      MLOPS_TEST: ${{ secrets.MLOPS_TEST }}
      DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug env
        run: |
          echo "Username is $DAGSHUB_USERNAME"
          echo "Token length is ${#MLOPS_TEST}"

      - name: Run DVC pipeline
        run: |
          dvc repro

      - name: Push DVC outputs to remote
        run: |
          dvc push
